# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48e1a769d76782e71fa105f1f65120fee5b1c586f0cd35860fcf5d78050feb22e0954d103086fb4e2d716b9d9584a9c449e1a1bba0ed64174f0950ef1ee8da9e

test:
  secret_key_base: f9ec65cdb078e53fb6fd826a9430ed03091bddf79f1f5bf9f2228d9ae0396f1ce18a05e8a1c02b8bdea3dfbeae1f7a595cdbbf255c3c13f7b830544932d47e4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
